version: '3'
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/CSABDD
      SPRING_DATASOURCE_USERNAME: moncef
      SPRING_DATASOURCE_PASSWORD: 18007022

  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: CSABDD
      POSTGRES_USER: moncef
      POSTGRES_PASSWORD: 18007022
